title: Î¼learn
tagline: Campus Activites
author:
  name: Vishakh Abhayan
  url: https://twitter.com/AbhayanVishakh

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Build Settings

paginate: 2

tags_path: /tags/
categories_path: /categories/
