title: μlearn
tagline: Campus Activites
author:
  name: μlearn
  url: https://mulearn.org

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Build Settings

paginate: 4

tags_path: /tags/
categories_path: /categories/
